### ISSUE TITLE
咨询，如何本地化部署呢？

### ISSUE THREAD

**Issue by taoweidong** [x-extends/vxe-table-docs#7]
咨询，如何本地化部署呢？是否有打包的dist文件提供给无法访问互联网的用户使用呢？

**Comment by dongasai** [comment]
可以看看这个 https://github.com/yingchaoOrg/local_docs-vxe-table-docs @taoweidong

**Comment by daling5248** [comment]
> 可以看看这个 https://github.com/yingchaoOrg/local_docs-vxe-table-docs @taoweidong

内网电脑这样使用，还是需要网络可咋办
